NumMessage:
  - num: 0
    text:
      - "当前无人在线"
      - "服务器现在没有人在线哦"
      - "没人诶..."
  - num: 1
    text:
      - "{0} 正在独自遨游世界"
      - "{0} 正在独自一人游玩"
  - num: 2
    text:
      - "{0} 和 {1} 正在体验二人世界"